services:
  redis:
    image: redis/redis-stack:7.2.0-v10
    container_name: msgbits-redis-dev
    ports:
      - "6379:6379"   # Redis
      - "8001:8001"   # RedisInsight UI
    volumes:
      - redis_data:/data

volumes:
  redis_data:
